### ISSUE TITLE
Crash when Attacking an Entity with a Punch (Empty hand)

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/bettercombat-extension#1]
[crash-2024-06-10_17.38.13-client.txt](https://github.com/user-attachments/files/15779343/crash-2024-06-10_17.38.13-client.txt)

Attacking an entity with an empty fist with Better Combat's one-handed punch animation results in a easily reproducible crash. Attacking an entity with a sword or any other weapon seems to not result in a crash. 

Probably something to do with RPG Inventory enabling combat with an empty hand (unsheathing mechanic).

**Comment by TheRedBrain** [comment]
Fixed in [version 1.5.1 of RPG Inventory](https://modrinth.com/mod/rpg-inventory/version/1.5.1)
