### ISSUE TITLE
"two_handed_pose" Does not Seem to Apply in Version 2.0.0 

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/bettercombat-extension#10]
The "two_handed_pose" field for a custom weapon_attributes file does not seem to work for version 2.0.0 with Better Combat 2.0.3+1.21.1, compared to previous versions (e.g. 1.3.0 with 1.8.6+1.20.1) when using the same datapack to edit the weapon_attributes. The cause is unknown to me, however, so please let me know of any questions you have.

**Comment by TheRedBrain** [comment]
How exactly does it not work?

The "two_handed_pose" is only used when several conditions are met:
- the "two_handed" value in the items weapon_attribute file is false
- the offhand is empty
- the "empty_offhand_equals_two_handing_mainhand" value in the "Better Combat Extension" server config is set to true

Are all those conditions met?

**Comment by InputandOutput** [comment]
Ah I see what went wrong. The option "empty_offhand_equals_two_handing_mainhand" wasn't enabled. =P

Closing issue then.
