### ISSUE TITLE
Attacking only uses the first part of the combo

### ISSUE THREAD

**Issue by Verdigrix** [TheRedBrain/bettercombat-extension#11]
Using release 1.3.0 for minecraft 1.20.1 on forge using the sinytra connector. When attacking with a weapon, only the first attack's animation plays. For example, using a vanilla sword just repeats the first slash, never progressing to the second slash or thrust.

**Comment by TheRedBrain** [comment]
Thanks for the report!

Will look into it

**Comment by Verdigrix** [comment]
I've been testing it on my own for a while, seems to be a weird interaction. I'll keep testing till I figure out what exactly is doing it and get back to you then.

**Comment by Verdigrix** [comment]
Seems to be an interaction between multiple mods at once. I'll continue testing and list what all breaks it once I find it, but this issue seems a bit too specific.

**Comment by TheRedBrain** [comment]
Okay, thanks for the testing!

**Comment by Verdigrix** [comment]
Seems that the fix GPU memory leak and Tactical Shield Overhaul mods are part of the issue, but isolated on their own they don't seem to cause any problems. Additionally, the Elytra Slot mod seems to break attack animations in a different way, speeding them up pretty heavily.

**Comment by Adidiii** [comment]
I don't think this is fixed...

**Comment by TheRedBrain** [comment]
Can you reproduce it in a minimal environment?

As in, only the mod and it's dependencies installed?

**Comment by Adidiii** [comment]
Of course! Should I have the Fabric version of the dependencies or the Forge version, as both seem to work.

**Comment by TheRedBrain** [comment]
I'm not sure, as I have no experience with the Connector mod.

Whatever the recommended procedure is, I guess :)

**Comment by Adidiii** [comment]
There's no real recommended procedure, I'll try both. Maybe the issue is with Forge dependencies working on a Fabric mod (or maybe even Fabric dependencies not being translated properly).

**Comment by DatBoiOmonie** [comment]
okay, after 3 days and 3 horrible nights of going thru my modpack, mod by mod.. i found BCE was not working in my modpack and continuously looping the first 1 hit animation, i found in my modpack instance atleast that SUPPLEMENTARIES version 1.20-3.1.21 on 1.20.1 forge using connector to run the mod seems to break, simply removing my supplementaries or removing BCE fixes my anim problem.
(edit: my BC version is the latest and BCE is the latest version)

**Comment by DatBoiOmonie** [comment]
i tried replicating the bug in another instance with just BC, BCE and supplementaries, while my animations wasn't looping the first attack like how my other 700 modpack was it however has my animations slowed and in a bugged state.

**Comment by DatBoiOmonie** [comment]
seems updating supplementaries doesn't fix the issue or anything, seems BCE is just incompatible.

**Comment by TheRedBrain** [comment]
Hi!
It is definitely possible that BCE and Supplementaries are simply not compatible, since the required setup by itself is not what I would call a staple environment.

BCE is quite experimental, as is Sinytra Connector (especially on 1.20.1). Supplementaries touches a lot of the games code, so it can easily interfere with other projects.

**Comment by DatBoiOmonie** [comment]
> Hi! It is definitely possible that BCE and Supplementaries are simply not compatible, since the required setup by itself is not what I would call a staple environment.
> 
> BCE is quite experimental, as is Sinytra Connector (especially on 1.20.1). Supplementaries touches a lot of the games code, so it can easily interfere with other projects.

Hello, i found the mod that was causing ACTUAL looping in my anims, similar to Verdigrix had they had gpumemoryleak be their issue, while i checked that mod and had no issues ALLTHELEAKS mod however completely bugged my swing animations and causing the first attack frame to continuously loop, seems like an incompatibility seems disabling alltheleaks fixed my animations and i can use better combat extension perfectly fine.
(edit: using the same bce and bc versions as i stated in an earlier post but my alltheleaks version is 1.0.6 and seems updating to 1.0.8 the latest version does not help)
