### ISSUE TITLE
More Dynamic Ways for Stamina/Mana Consumption

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/bettercombat-extension#4]
There are several ideas that would make stamina/mana consumption correspond with certain types of spells:
- Stamina/mana consumption rate for spells that attack using the "casting" phase.
- Stamina/mana consumption when a spell's status effect is applied and active. 
- More stamina/mana consumption the more times a spell is casted in succession or a set period of time. 
- Multiplying/addition of costs to spells via attributes/status effects (e.g. another mod's status effect doubling stamina cost?).

**Comment by TheRedBrain** [comment]
I suggest you make this an issue for Spell Engine Extension :)

**Comment by InputandOutput** [comment]
Oops
