### ISSUE TITLE
will it be for "forge"?

### ISSUE THREAD

**Issue by Kraygan** [TheRedBrain/bettercombat-extension#7]
I really like this mod, you're just a genius

**Comment by TheRedBrain** [comment]
Thank you!

Currently I have no plans to port any of my mods to another mod loader.
I just don't have the time for it.

That does not mean I will never do it. Just that many things have a higher priority for me.

Have you ever heard of the "Sinytra Connector" mod?
While it is highly experimental, when it works, it allows to install Fabric mods in a Forge instance
