### ISSUE TITLE
Please add this for 1.19.2!

### ISSUE THREAD

**Issue by Mortis10** [TheRedBrain/bettercombat-extension#8]
This is EXACTLY what I'm looking to add to my server, is 1.19.2 an option?

**Comment by Mortis10** [comment]
Also, on Forge

**Comment by TheRedBrain** [comment]
Hi!
I experimented with maintaining support for multiple versions for some of my mods. I found that it is not worth the extra time and effort for me. I have a limited amount of time I can spend on modding and I'd rather spend that time on supporting the current version of the game and on creating new mods.
Adding support for Forge is a similar problem. Additionally I would have to rewrite large parts of the mod. I make heavy use of mixins, which are (to my knowledge) not supported by Forge.
I hope my reasons are understandable.
