### ISSUE TITLE
"Damage Type" FIeld in Parent "weapon_attributes" File does not Carry Over to Other Weapon Files 

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/bettercombat-extension#9]
When the damage type field is defined in a custom parent file, the damage type is not carried over to other items' files in the weapon_attributes directory that are assigned to the parent file (i.e. the spear.json file with a damage type of piercing does not result in the damage type being applied to all weapons with a parent file of "spear"). Defining the damage type for an item's file in the weapon_attributes directory works, however. 

Being able to assign a "class" of weapons with a dedicated damage type for an attack may help with compatibility without having to assign damage types for every single weapon in the game.

**Comment by TheRedBrain** [comment]
Hi!

I will look into this!

Thanks for reporting!

**Comment by TheRedBrain** [comment]
I just realised that this is in the wrong repository

The issue has nothing to do with this mod, but with "Better Combat Extension"

**Comment by InputandOutput** [comment]
Oops, my bad.

**Comment by TheRedBrain** [comment]
no worries
